version: '2'

networks:
  ros:
    driver: bridge

services:
  ros-master:
    image: osrf/ros:noetic-desktop-full
    command: stdbuf -o L roscore
    networks:
      - ros
    restart: always
  
  ros-bridge:
    build: 
      context: .
      dockerfile: Dockerfile-ros-bridge
    depends_on:
      - ros-master
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
    networks:
      - ros
    ports:
      - 9090:9090
    restart: always

  webviz:
    image: cruise/webviz:latest
    depends_on:
      - ros-bridge
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
    networks:
      - ros
    ports:
      - 8080:8080
    restart: always

  gzweb:
    build:
      context: .
      dockerfile: Dockerfile-gzweb
    depends_on:
      - ros-workspace
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "GAZEBO_MASTER_URI=http://ros-workspace:11345"
    networks:
      - ros
    ports:
      - 8181:8181
    restart: always
  
  ros-workspace:
    build: 
      context: .
      dockerfile: Dockerfile-ros-workspace
    depends_on:
      - ros-master
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
    networks:
      - ros
    restart: always

  ssh: 
    build: 
      context: .
      dockerfile: Dockerfile-ssh
    depends_on:
      - ros-master
    tty: true
    stdin_open: true
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
    networks:
      - ros
    ports:
      - 2222:22
    restart: always