FROM osrf/ros:noetic-desktop-full
SHELL [ "/bin/bash", "-ci" ]

RUN apt-get update && apt-get install -q -y --no-install-recommends python3-catkin-tools \
ros-noetic-catkin python3-rosdep xvfb
RUN /bin/bash -c "source /opt/ros/noetic/setup.bash \
&& mkdir ros_ws && cd ros_ws/ && mkdir src \
&& catkin init \
&& catkin build"
