FROM osrf/ros:noetic-desktop-full

RUN apt update && apt install -y openssh-server
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

RUN useradd -m -s /bin/bash ros
RUN echo "ros:admin" | chpasswd
RUN adduser ros sudo
RUN apt-get install ros-noetic-teleop-twist-keyboard
EXPOSE 22

ENTRYPOINT service ssh start && bash